[tool.black]
line-length = 120
target-version = ['py310', 'py311']
include = '''
(
    scripts/.*
    |
    hidiffusion/.*
)\.py$
'''
exclude = '''
(
    \.git
    | \.venv
    | build
    | dist
    | \.eggs
)
'''